language: objective-c
before_script:
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
script:
- xctool -workspace Ligger.xcworkspace -scheme Ligger -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
env:
  global:
  - BUILD_OFFSET="0"
  - RELEASE_VERS="true"
  - APP_NAME="Ligger"
  - 'DEVELOPER_NAME="iPhone Distribution: Fezzee Corp."'
  - PROFILE_NAME="XC_Ad_Hoc_comfezzee"
  - INFO_PLIST="Source/Resources/Platforms/IOS/Info.plist"
  - BUNDLE_DISPLAY_NAME="Ligger"
  - BUNDLE_IDENTIFIER="com.fezzee.Ligger"
  - secure: NRd8mZYK0EoGO1iXyG1X9CSuWDgC1FLYSQLdk4tGPgoEd9JApNDH8dkgbqwf9VehBBCHat51JkLhzJEAcJc5JBvMtXlG7uC6p+aOVl9+zfCFhfZzYdawJau4DyUM8sZr1Qjv8fvubntj70a9CJPLyudVwjA67ZyOFPfnt6cQqHE=
